### ISSUE TITLE
连点时会有重复可能

### ISSUE THREAD

**Issue by limuy2022** [Yish1/ktdmq#1]
建议使用set来去重

**Comment by Yish1** [comment]
目前学业繁忙，无暇顾及，555~~~

**Comment by limuy2022** [comment]
那我帮你解决吧，我会提个pr，记得通过(主要使用了你的代码，顺便感谢一下)

**Comment by Yish1** [comment]
好的，感谢你！！！不过我是高三党，后天返校，下次回家大概是国庆节...也可能是两周后

**Comment by limuy2022** [comment]
哈哈，不瞒你说，其实我是初三党

**Comment by Yish1** [comment]
ohhhh！捕捉大佬

**Comment by Yish1** [comment]
确实排除了重复，不过在超出最大数字后会崩溃，可以加个提示不超过最大人数

**Comment by Yish1** [comment]
或者是限制输入最大数字

**Comment by Yish1** [comment]
ok了，我把限制做好了

**Comment by Yish1** [comment]
在吗？还有其他联系方式吗？发现修改后存在一些问题

**Comment by limuy2022** [comment]
在，有微信angelgel2020，请问存在什么问题？
